config/routes.rb
Rails.application.routes.draw do
  resources :listings, only: [:index, :update]
  resources :searches
  resources :settings, only: [:index, :edit, :update]

  root to: redirect("/listings")
end

app/models/bart_station.rb
class BartStation < ActiveRecord::Base
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :bart_station
  belongs_to :user

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  def self.interested
    where(are_interested: true)
  end

  def self.pending
    where(are_interested: nil)
  end

  def self.for_settings(user_settings)
    transit_max_time(user_settings.transit_max_time)
      .walk_score_minimum(user_settings.walk_score_minimum)
      .transit_score_minimum(user_settings.transit_score_minimum)
      .bike_score_minimum(user_settings.transit_score_minimum)
      .personal_crime_grade_minimum(user_settings.personal_crime_grade_minimum)
      .property_crime_grade_minimum(user_settings.property_crime_grade_minimum)
  end

  def self.order_by_price_and_transit_time
    order(price: :asc, transit_travel_in_minutes: :asc)
  end

  def self.bart_max_distance(distance)
    where("bart_distance is null OR bart_distance <= ?", distance)
  end

  def self.transit_max_time(minutes)
    where(
      "transit_travel_in_minutes is null OR transit_travel_in_minutes <= ?",
      minutes
    )
  end

  def self.walk_score_minimum(minutes)
    score_minimum(:walk, minutes)
  end

  def self.transit_score_minimum(minutes)
    score_minimum(:transit, minutes)
  end

  def self.bike_score_minimum(minutes)
    score_minimum(:bike, minutes)
  end

  def self.personal_crime_grade_minimum(grade)
    grade_minimum(:personal, grade)
  end

  def self.property_crime_grade_minimum(grade)
    grade_minimum(:property, grade)
  end

  def user_settings
    user.settings
  end

  private

  def self.score_minimum(type, value)
    where("#{type}_score is null OR #{type}_score >= ?", value)
  end

  def self.grade_minimum(type, grade)
    key = "#{type}_crime_grade"
    accepted_grades = [grade] + higher_grades(grade)
    query_formatted_grades = accepted_grades.map { |g| "'#{g}'" }.join(', ')
    # SQL-injection vulnerability!!!
    # Not sure of a good way to generate this query
    where("#{key} is null OR #{key} IN (#{query_formatted_grades})")
  end

  def self.higher_grades(grade)
    case grade
    when "A"
      []
    when "B"
      ["A"]
    when "C"
      ["A", "B"]
    when "D"
      ["A", "B", "C"]
    when "F"
      ["A", "B", "C", "D"]
    end
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :description
  validates :url, presence: true, url: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user

  REGISTERED_SETTINGS = [
    :bart_max_distance,
    :email_body,
    :transit_max_time,
    :walk_score_minimum,
    :transit_score_minimum,
    :bike_score_minimum,
    :personal_crime_grade_minimum,
    :property_crime_grade_minimum,
  ]

  def self.register_setting_getters
    self.class.instance_eval do
      REGISTERED_SETTINGS.each do |setting_name|
        define_method(setting_name) { find_by!(name: setting_name).value }
      end
    end
  end
  register_setting_getters
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :searches
  has_many :settings
  has_many :listings

  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  before_filter :authorize

  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
require "listing_emailer"

class ListingsController < ApplicationController
  def index
    @pending_listings = current_user.
      listings.
      pending.
      for_settings(current_user.settings).
      order_by_price_and_transit_time

    @interested_listings = current_user.
      listings.
      interested.
      order_by_price_and_transit_time
  end

  def update
    listing = Listing.find(params[:id])
    if listing.update(listing_params)
      if params[:email]
        redirect_to ListingEmailer.new(listing).mailto
      else
        redirect_to listings_path, notice: "Listing updated."
      end
    else
      flash[:error] = "Listing not updated."
      redirect_to listings_path
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:are_interested, :has_contacted)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:edit, :update, :destroy]

  def index
    @searches = current_user.searches
  end

  def new
    @search = current_user.searches.build
  end

  def edit
  end

  def create
    @search = current_user.searches.build(search_params)

    if @search.save
      redirect_to searches_path, notice: "New search added."
    else
      render :new
    end
  end

  def update
    if @search.update(search_params)
      redirect_to searches_path, notice: "Search updated."
    else
      render :edit
    end
  end

  def destroy
    @search.destroy
    redirect_to searches_url, notice: "Search removed."
  end

  private

  def set_search
    @search = current_user.searches.find(params[:id])
  end

  def search_params
    params.require(:search).permit(:description, :url, :enabled)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @settings = current_user.settings
  end

  def edit
    @setting = current_user.settings.find(params[:id])
  end

  def update
    @setting = current_user.settings.find(params[:id])

    if @setting.update(setting_params)
      redirect_to settings_path, notice: "Setting updated."
    else
      render :edit
    end
  end

  private

  def setting_params
    params.require(:setting).permit(:value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(content)
    content_for :title, content
  end

  def nav_link_to(content, url)
    klass = request.path.include?(url) ? "active" : nil
    content_tag :li, class: klass do
      link_to content, url
    end
  end

  def icon(name)
    content_tag :span,
                "",
                class: "glyphicon glyphicon-#{name}",
                "aria-hidden" => true
  end

  def alert_class_for(id)
    case id
    when "notice"
      "alert-success"
    when "error"
      "alert-danger"
    else
      "alert-info"
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def tr_class_for_listing(listing)
    if listing.unlisted
      "danger"
    elsif listing.has_contacted
      "info"
    end
  end

  def maybe(value)
    value || "-"
  end

  def walk_score_info(listing)
    walk = maybe(listing.walk_score)
    transit = maybe(listing.transit_score)
    bike = maybe(listing.bike_score)

    "#{walk} / #{transit} / #{bike}"
  end

  def crime_rating_info(listing)
    personal = maybe(listing.personal_crime_grade)
    property = maybe(listing.property_crime_grade)

    "#{personal} / #{property}"
  end
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Culling Home", root_path, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="collapse navbar-collapse">

      <% if signed_in? %>
        <%= form_tag sign_out_path, method: :delete, class: "navbar-form navbar-right" do %>
          <div class="form-group">
            <%= current_user.email %>
          </div>
          <button type="submit" class="btn">Sign out</button>
        <% end %>

        <ul class="nav navbar-nav">
          <%= nav_link_to "Listings", listings_path %>
          <%= nav_link_to "Searches", searches_path %>
          <%= nav_link_to "Settings", settings_path %>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag %>
  <%= yield :head %>

  <% if content_for? :title %>
    <title><%= yield :title %> ・ Culling Home </title>
  <% else %>
    <title>Culling Home</title>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/menu" %>

  <div class="container">
    <div id="alerts">
      <% flash.each do |id, message| %>
        <div class="alert alert-dismissible <%= alert_class_for id %>" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <%= icon "remove" %>
          </button>
          <%= message %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/listings/_table.html.erb
<% if listings.any? %>
  <table id="<%= id %>" class="table table-striped listings">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Transit</th>
        <th>Walk/Transit/Bike</th>
        <th>Crime</th>
        <th>Neighborhood</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% listings.each do |listing| %>
        <%= content_tag_for :tr, listing, class: tr_class_for_listing(listing) do %>
          <td><%= link_to listing.title, listing.href %></td>
          <td><%= number_to_currency listing.price, precision: 0 %></td>
          <td>
            <% if listing.transit_travel_in_minutes %>
              <%= link_to "#{listing.transit_travel_in_minutes.round} mins", listing.transit_directions_url %>
            <% else %>
              ---
            <% end %>
          </td>
          <td><%= walk_score_info(listing) %></td>
          <td><%= crime_rating_info(listing) %> </td>
          <td><%= listing.neighborhood %></td>
          <td class="text-right">
            <% if listing.are_interested && !listing.has_contacted %>
              <% if listing.email %>
                <%= link_to icon("envelope"), listing_path(listing, email: true, listing: { has_contacted: true }), class: "btn btn-xs btn-primary", method: :patch %>
              <% else %>
                <%= link_to icon("phone"), listing_path(listing, listing: { has_contacted: true }), class: "btn btn-xs btn-primary", method: :patch %>
              <% end %>

            <% end %>

            <% if listing.are_interested.nil? %>
              <%= link_to icon("ok"), listing_path(listing, listing: { are_interested: true }), class: "btn btn-xs btn-success", method: :patch %>
            <% end %>

            <%= link_to icon("remove"), listing_path(listing, listing: { are_interested: false }), class: "btn btn-xs btn-danger", method: :patch %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>

<% else %>
  <div class="jumbotron">
    <h2>Nothing here!</h2>
    <p class="lead">You're all caught up.</p>
  </div>
<% end %>

app/views/listings/index.html.erb
<% content_for :head do %>
  <meta http-equiv="refresh" content="600" />
<% end %>

<% title "Listings (#{@pending_listings.count})" %>

<div class="row">
  <div class="col-md-12">
    <h1>Interested (<%= @interested_listings.count %>)</h1>
    <%= render partial: "table", locals: { listings: @interested_listings, id: "interested" } %>
  </div>

  <div class="col-md-12">
    <h1>Pending (<%= @pending_listings.count %>)</h1>
    <%= render partial: "table", locals: { listings: @pending_listings, id: "pending" } %>
  </div>
</div>

app/views/searches/_form.html.erb
<%= form_for @search, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @search.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/searches/edit.html.erb
<% title "Edit Search #{@search.id}" %>

<div class="row header-row">
  <div class="col-md-8">
    <h1>Edit Search</h1>
  </div>

  <div class="col-md-4">
    <div class="text-right">
      <%= link_to "Cancel", searches_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>

<div class="row header-row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/searches/index.html.erb
<% title "Searches" %>

<div class="row header-row">
  <div class="col-md-8">
    <h1>Searches</h1>
  </div>

  <div class="col-md-4">
    <div class="text-right">
      <%= link_to new_search_path, id: "new-search", class: "btn btn-success" do %>
        <%= icon "plus" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @searches.any? %>
      <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Description</th>
          <th>Url</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @searches.each do |search| %>
          <tr>
            <td>
              <% if search.enabled %>
                <%= link_to icon("pause"), search_path(search, search: { enabled: false }), method: :patch, class: "text-danger disable-search" %>
              <% else %>
                <%= link_to icon("play"), search_path(search, search: { enabled: true }), method: :patch, class: "text-success enable-search" %>
              <% end %>
            </td>
            <td><%= search.description %></td>
            <td><%= link_to search.url.truncate(40), search.url %></td>
            <td class="text-right">
              <%= link_to icon("pencil"), edit_search_path(search), class: "edit-search btn btn-xs btn-warning" %>
              <%= link_to icon("remove"), search, method: :delete, class: "delete-search btn btn-xs btn-danger", data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <div class="jumbotron">
        <h2>Nothing here!</h2>
        <p class="lead">You should add something.</p>
        <%= link_to "Add a search", new_search_path, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/searches/new.html.erb
<% title "Add Search" %>

<div class="row header-row">
  <div class="col-md-8">
    <h1>Add Search</h1>
  </div>

  <div class="col-md-4">
    <div class="text-right">
      <%= link_to "Cancel", searches_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>

<div class="row header-row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/settings/_form.html.erb
<%= form_for @setting, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @setting.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :value, @setting.name.humanize, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :value, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/settings/edit.html.erb
<% title "Edit Setting #{@setting.name.humanize}" %>

<div class="row header-row">
  <div class="col-md-8">
    <h1>Edit Setting</h1>
  </div>

  <div class="col-md-4">
    <div class="text-right">
      <%= link_to "Cancel", settings_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>

<div class="row header-row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/settings/index.html.erb
<% title "Settings" %>

<h1>Settings</h1>

<div class="row">
  <div class="col-md-12">
  <table class="table table-striped listings">
    <thead>
      <tr>
        <th>Name</th>
        <th>Value</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @settings.each do |setting| %>
        <%= content_tag_for :tr, setting do %>
          <td><%= setting.name.titleize %></td>
          <td><%= setting.value %></td>
          <td class="text-right">
            <%= link_to icon("pencil"), edit_setting_path(setting), class: "edit-setting btn btn-xs btn-warning" %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/users/_form.html.erb
  <div class="form-group">
    <%= form.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :email, class: "form-control", type: "email" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.password_field :password, class: "form-control" %>
    </div>
  </div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user, html: { class: "form-horizontal", role: "form" } do |form| %>
    <%= render :partial => '/users/form', :object => form %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-1">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>